
### GET request to example server
POST http://localhost:3000/api/slack/screen-capture
Content-Type: application/json

{
  "dashboardUrl": "/d/e661a41f-3a40-400e-b985-8088e0292b9b/stg-jvm-micrometer",
  "event": {
    "type" : "app_mention",
    "channel": "C085T1LTVHQ"
  }
}

### GET request to example server
GET http://localhost:3000


### GET request to example server
POST https://luminary-kappa.vercel.app/api/slack/events
Content-Type: application/json

{
  "token": "verification-token",
  "challenge": "3eZbrw1aBz7OB7rSRFwhphJ5gXgiDKhNRJzdTJS5Sn3",
  "type": "url_verification"
}


### GET request to example server
POST https://slack.com/api/files.getUploadURLExternal
Authorization: Bearer xx
Content-Type: application/x-www-form-urlencoded; charset=utf-8

filename=filename.png&length=123
